#!/usr/bin/env python3
"""
ScholarLib-EM Index Generator
Scans all paper directories and generates a consolidated BibTeX bibliography file.
"""

import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
PAPERS_DIR = REPO_ROOT / "papers"
OUTPUT_FILE = REPO_ROOT / "references.bib"


def collect_bib_entries():
    """Walk through all paper directories and collect .bib files."""
    entries = []
    for bib_file in sorted(PAPERS_DIR.rglob("*.bib")):
        rel_path = bib_file.relative_to(REPO_ROOT)
        try:
            content = bib_file.read_text(encoding="utf-8")
            entries.append({
                "path": str(rel_path),
                "content": content.strip()
            })
        except Exception as e:
            print(f"Warning: Could not read {rel_path}: {e}")
    return entries


def generate_index(entries):
    """Generate the consolidated .bib file."""
    lines = []
    lines.append("% ScholarLib-EM — Consolidated Bibliography")
    lines.append("% Auto-generated by scripts/generate_index.py")
    lines.append(f"% Total entries: {len(entries)}")
    lines.append("%")
    lines.append("% Usage: Copy this file or individual entries into your .bib file")
    lines.append("%")
    lines.append("")

    for entry in entries:
        lines.append(f"% Source: {entry['path']}")
        lines.append(entry["content"])
        lines.append("")

    return "\n".join(lines)


def generate_stats(entries):
    """Generate statistics by year and category."""
    stats = {}
    for entry in entries:
        parts = Path(entry["path"]).parts
        if len(parts) >= 2:
            year = parts[0]
            category = parts[1]
            key = f"{year}/{category}"
            stats[key] = stats.get(key, 0) + 1
    return stats


def main():
    print("Scanning papers directory...")
    entries = collect_bib_entries()
    print(f"Found {len(entries)} BibTeX entries.")

    # Generate consolidated .bib
    bib_content = generate_index(entries)
    OUTPUT_FILE.write_text(bib_content, encoding="utf-8")
    print(f"Written to {OUTPUT_FILE}")

    # Print stats
    stats = generate_stats(entries)
    if stats:
        print("\n--- Paper Statistics ---")
        for key, count in sorted(stats.items()):
            print(f"  {key}: {count} papers")

    print("\nDone!")


if __name__ == "__main__":
    main()
